export const getData = function () {
  return [
    {
      "idProduct": 123001, //number
      "nameProduct": "someName", //string
      "category": "TV", // tv computers laptop tablets monitor cellPhone apple games app speakers headphones homeApp werrTechn
      "modelNumber": "ABC0011df123",
      "price": 350, //Daniyar number
      "shipping": "Free", // or pickup, 
      "year": 2019, // Aichurok 2018-2020-2021-2022
      "brand": "Sony", // HP Lenovo, Toshiba, LG, Samsung, Sony, Microsoft
      "type": "Curved", // Curved flat Smart
      "displayType": "Full HD", // Gulzat LED OLED HD 4K  4k-ULTRA-HP
      "screenSize": 32, // Talha 32-40-43-50-55-70-75-85
      "color": "Silver", // Talha  black, gold, gray, white
      "storageType": "SSD",
      "storage": 256, // 512GB -1TB
      "memoryRAM": 8, // 4-16-32 GB
      "processorModel": "Intel Core i3", // i5 i7 i9 AMD Ryzen 3-5-7 Apple M1-pro IntelPentium
      "screenResolution": "1600 x 900", // 3840 x 2160(4K) 3456 x 2234 3000x2000 
      "touchScreen": true, // false
      "productWeight": 3.75,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454108_sd.jpg",
    },


    {
      "idProduct": 123002,
      "nameProduct": "Smart LED 1920 x 1080",
      "category": "Computers",
      "modelNumber": "XE350XBA-K01US",
      "price": 299,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "type": "Smart",
      "displayType": "LED",
      "screenSize": 15.6,
      "color": "Platinum Titan",
      "storageType": "SSD",
      "memoryRAM": 16,
      "processorModel": "Intel Celeron",
      "screenResolution": "1920 x 1080",
      "touchScreen": false,
      "productWeight": 3.75,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6371/6371532_sd.jpg;maxHeight=640;maxWidth=550",
    },

    {
      "idProduct": 123003,
      "nameProduct": "MacBook Pro",
      "category": "Computers",
      "modelNumber": "MWP42LL/A",
      "price": 1299.99,
      "shipping": "Free",
      "year": 2020,
      "brand": "Apple",
      "displayType": "Retina Display",
      "screenSize": 13.3,
      "color": "Space gray",
      "storageType": "SSD",
      "memoryRAM": 16,
      "processorModel": "Intel 10th Generation Core i5",
      "screenResolution": "2560 x 1600 ",
      "touchScreen": false,
      "productWeight": 3.1,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6287/6287726_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123004,
      "nameProduct": "Dell",
      "category": "Computers",
      "modelNumber": "G7700-7231BLK-PUS",
      "price": 1444,
      "shipping": "Free",
      "year": 2020,
      "brand": "Dell",
      "displayType": "LED",
      "screenSize": 17.3,
      "color": "Black",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 16,
      "processorModel": "Intel 10th Generation Core i7",
      "screenResolution": "1920 x 1080",
      "touchScreen": false,
      "productWeight": 6.53,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6416/6416473_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123005,
      "nameProduct": "Lenovo",
      "category": "Computers",
      "modelNumber": "82ND006QUS/82ND0002US",
      "price": 699,
      "shipping": "Free",
      "year": 2021,
      "brand": "Lenovo",
      "displayType": " Full HD",
      "screenSize": 13.3,
      "color": "Abyss Blue with Fabric Cover",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 16,
      "processorModel": "AMD Ryzen 7 5000 Series",
      "screenResolution": "1920 x 1080",
      "touchScreen": true,
      "productWeight": 2.99,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455180_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123006,
      "nameProduct": "Asus",
      "category": "Computers",
      "modelNumber": "GU502LV-BI7N8",
      "price": 1317,
      "shipping": "Free",
      "year": 2018,
      "brand": "Asus",
      "displayType": "LED",
      "screenSize": 15.6,
      "color": "Prism Black",
      "storageType": "SSD",
      "storage": 1024,
      "memoryRAM": 16,
      "processorModel": "i7-10750H",
      "screenResolution": "3840 x 2160",
      "touchScreen": false,
      "productWeight": 4.43,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6403/6403817_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123007,
      "nameProduct": "HP",
      "category": "Computers",
      "modelNumber": "15-dy2073dx",
      "price": 729.99,
      "shipping": "Free",
      "year": 2021,
      "brand": "HP",
      "displayType": "LED",
      "screenSize": 15.6,
      "color": "Natural Silver",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 16,
      "processorModel": "i7-1165G7",
      "screenResolution": "1920 x 1080",
      "touchScreen": true,
      "productWeight": 3.75,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477889_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123008,
      "nameProduct": "Acer",
      "category": "Computers",
      "modelNumber": "CB311-11H-K04N",
      "price": 129,
      "shipping": "Free",
      "year": 2021,
      "brand": "Acer",
      "displayType": "LED",
      "screenSize": 11.6,
      "color": "Silver",
      "storageType": "SSD eMMC",
      "storage": 256,
      "memoryRAM": 16,
      "processorModel": "MediaTek",
      "screenResolution": "1366 x 768",
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6471/6471196_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123009,
      "nameProduct": "UR55 Series 28 IPS 4K UHD Monitor",
      "category": "Computers",
      "modelNumber": "LU28R550UQNXZA",
      "price": 269.99,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "displayType": "LCD",
      "screenSize": 28,
      "color": "Black",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "3840 x 2160",
      "productHeight": 14.7,
      "productWidth": "25.1",
      "standIncluded": true,
      "productWeight": 12.8,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6386/6386391_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123010,
      "nameProduct": "ASUS - TUF 23.8” FHD 1ms FreeSync Gaming Monitor (HDMI)",
      "category": "Computers",
      "modelNumber": "VG246H",
      "price": 179.99,
      "shipping": "Free",
      "year": 2021,
      "brand": "Asus",
      "displayType": "LED",
      "screenSize": 23.8,
      "color": "Black",
      "storageType": "SSD",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i7",
      "screenResolution": "1920 x 1080",
      "productHeight": 14.7,
      "productWidth": 21.46,
      "touchScreen": true,
      "productWeight": 13.36,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6450/6450752_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123011,
      "nameProduct": "35” Curved UltraWide QHD Monitor with USB Type C Connectivity",
      "category": "Computers",
      "modelNumber": "35WN75C-B",
      "price": 499.99,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "displayType": "LED",
      "screenSize": 35,
      "color": "Black",
      "storageType": "SSD",
      "storage": 1024, // 512GB -1TB
      "memoryRAM": 32,
      "processorModel": "Intel Core i7",
      "screenResolution": "3440 x 1440",
      "productHeight": 18.2,
      "productWidth": 32.7,
      "productWeight": 18.3,
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6437/6437477_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123012,
      "nameProduct": "35” Curved UltraWide QHD Monitor with USB Type C Connectivity",
      "category": "Computers",
      "modelNumber": "66C0KCC3US",
      "price": 499.99,
      "shipping": "Free",
      "year": 2021,
      "brand": "Lenovo",
      "displayType": "LED",
      "screenSize": 23.8,
      "color": "Black",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 16,
      "processorModel": "Intel Core i5",
      "screenResolution": "1920 x 1080",
      "productHeight": 12.78,
      "productWidth": 21.28,
      "productWeight": 9.92,
      "curevedScreen": false,
      "standIncluded": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453641_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // 
    //LG -6453968
    {
      "idProduct": 123013,
      "nameProduct": " 43/Class UP7000 Series LED 4K UHD Smart webOS TV",
      "category": "TV",
      "modelNumber": "UP7000",
      "price": 1329.99,
      "shipping": "Free",
      "year": 2020,
      "brand": "LG",
      "type": "Smart",
      "displayType": "LED",
      "screenSize": 43,
      "color": "Black",
      "storage": 300,
      "memoryRAM": 10,
      "processorModel": "Intel Core i3",
      "screenResolution": "1100 x 2000",
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453968_sd.jpg;maxHeight=640;maxWidth=550",

    },
    //SONY -6453208
    {
      "idProduct": 123014,
      "nameProduct": "65/Class BRAVIA XR X90J Series LED 4K UHD Smart Google TV",
      "category": "TV",
      "modelNumber": "X9OJ",
      "price": 1199.99,
      "shipping": "pickup",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "displayType": "LED",
      "screenSize": 65,
      "color": "Black",
      "storage": 250,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "850 x 950",
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453208_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung - 6480602
    {
      "idProduct": 123015,
      "nameProduct": "75/Class QN84A Neo QLED 4K UHD Smart Tizen TV",
      "category": "TV",
      "modelNumber": "X9OJ",
      "price": 2649.99,
      "shipping": "Free",
      "year": 2020,
      "brand": "Samsung",
      "displayType": "Smart",
      "screenType": "LED",
      "screenSize": 75,
      "color": "Black",
      "storage": 300,
      "memoryRam": 14,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6480/6480602cv20d.jpg;maxHeight=640;maxWidth=550",
    },
    // LG-6452992
    {
      "idProduct": 123016,
      "nameProduct": "70/Class UP8070 Series LED 4K UHD Smart webOS TV",
      "category": "TV",
      "modelNumber": "70UP8070PUA",
      "price": 2649.99,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "type": "Smart",
      "displayType": "LED",
      "screenSize": 70,
      "color": "Black",
      "storage": 300,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452992_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung -6401735
    {
      "idProduct": 123017,
      "nameProduct": " 65/Class C1 Series OLED 4K UHD Smart webOS TV",
      "category": "TV",
      "modelNumber": "OLED65C1PUB",
      "price": 399.99,
      "shipping": "pickup",
      "year": 2021,
      "brand": "Samsung",
      "displayType": "LED",
      "screenSize": 64.5,
      "color": "Black",
      "storage": 300,
      "memoryRam": 16,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6401/6401735_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // LG 6453312
    {
      "idProduct": 123018,
      "nameProduct": "65/Class C1 Series OLED 4K UHD Smart webOS TV",
      "category": "TV",
      "modelNumber": "OLED65C1PUB",
      "price": 399.99,
      "shipping": "pickup",
      "year": 2021,
      "brand": "LG",
      "displayType": "OLED",
      "screenSize": 64.5,
      "color": "Black",
      "storage": 250,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453312_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung -6453192
    {
      "idProduct": 123019,
      "nameProduct": "43/Class Q60A Series QLED 4K UHD Smart Tizen TV ",
      "category": "TV",
      "modelNumber": "QN43Q60AAFXZA",
      "price": 499.99,
      "shipping": "pickup",
      "year": 2021,
      "brand": "Samsung",
      "displayType": "Edge LIT",
      "screenSize": 64.5,
      "color": "Titan gray",
      "storage": 250,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453192_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // LG-6454719
    {
      "idProduct": 123020,
      "nameProduct": "65 / Class UP7000 Series LED 4K UHD Smart webOS TV ",
      "category": "TV",
      "modelNumber": "65UP7000PUA",
      "price": 499.99,
      "shipping": "Free",
      "year": 2021,
      "brand": "LG",
      "displayType": "Edge LIT",
      "screenSize": 64.5,
      "color": "Black",
      "storage": 300,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454719_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung -6401740
    {
      "idProduct": 123021,
      "nameProduct": " 43/Class 7 Series LED 4K UHD Smart Tizen TV",
      "category": "TV",
      "modelNumber": "UN43TU7000FXZA",
      "price": 350.99,
      "shipping": "Free",
      "year": 2018,
      "brand": "Samsung",
      "displayType": "Direct LIT",
      "screenSize": 43,
      "color": "Titan gray",
      "storage": 250,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6401/6401740_sd.jpg;maxHeight=640; maxWidth=550",
    },

    {
      "idProduct": 123022,
      "nameProduct": " 50/Class F30 Series LED 4K UHD Smart Fire TV",
      "category": "TV",
      "modelNumber": "NS-50F301NA22",
      "price": 349.99,
      "shipping": "pickup",
      "year": 2021,
      "brand": "Insignia™",
      "displayType": "Direct LIT",
      "screenSize": 49.5,
      "color": "Black",
      "storage": 250,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6456/6456970_sd.jpg;maxHeight=640;maxWidth=550"

    },
    // Sony - 6455218
    {
      "idProduct": 123023,
      "nameProduct": "65/Class BRAVIA XR A80J Series OLED 4K UHD Smart Google TV ",
      "category": "TV",
      "modelNumber": "XR65A80J",
      "price": 2199.99,
      "shipping": "pickup",
      "year": 2021,
      "brand": "Sony",
      "displayType": "OLED",
      "screenSize": 69,
      "color": "Black",
      "storage": 250,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455218_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123024,
      "nameProduct": "32/ Class F20 Series LED HD Smart Fire TV",
      "category": "TV",
      "modelNumber": "NS-32DF310NA19",
      "price": 149.99,
      "shipping": "pickup",
      "year": 2018,
      "brand": "Insignia™",
      "displayType": "Standard LED",
      "screenSize": 69,
      "color": "Black",
      "storage": 300,
      "memoryRam": 32,
      "processorModel": "Intel Core i2",
      "screenResolution": "1200 x 1300",
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6247/6247254_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // samsung -6452966
    {
      "idProduct": 6252966,
      "nameProduct": "43\" Class 8000 Series LED 4K UHD Smart Tizen TV ",
      "category": "TV",
      "modelNumber": " UN43AU8000FXZA",
      "brand": "Samsung",
      "year": 2021,
      "color": "Black",
      "series": "8000",
      "price": 499.99,
      "screenResolution": "HD(720p)",
      "screenSize": 32,
      "displayType": "Standard LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amazon Alexa",
      "box-size": "26.8(H), 42.7(w),4.9(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452966cv12d.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung- 6451478
    {
      "idProduct": 6451478,
      "nameProduct": "65\" Class Q80A Series QLED 4K UHD Smart Tizen TV ",
      "category": "TV",
      "modelNumber": "QN65Q80AAFXZA",
      "brand": "Samsung",
      "year": 2021,
      "color": "Titan black",
      "series": "Q80",
      "price": 1399.99,
      "screenResolution": '4K(2160p)',
      "screenSize": 65,
      "displayType": "LED",
      "Smart capable": "Yes",
      "Backlight Type": "Full Array Local Dimming",
      "voice assistant": "Amazon Alexa,GoogleAssistant(Bixby",
      "box-size": "38(H), 63.8(w), 8.4(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6451/6451478_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung- 6453024
    {
      "idProduct": 6453024,
      "nameProduct": "65\" Class 8000 Series LED 4K UHD Smart Tizen TV",
      "category": "TV",
      "modelNumber": "UN65AU8000FXZA",
      "brand": "Samsung",
      "year": 2021,
      "color": "Black",
      "series": "8000",
      "price": 799.99,
      "screenResolution": '4K(2160p)',
      "screenSize": 65,
      "displayType": "LED",
      "Smart capable": "Yes",
      "Backlight Type": "Full Array Local Dimming",
      "voice assistant": "Bixby,Google Assistant",
      "box-size": "37.4(H), 63.5(w), 65(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453024_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      // Samsung 642916
      "idProduct": 642916,
      "nameProduct": " 70\" Class 7 Series LED 4K UHD Smart Tizen TV",
      "category": "TV",
      "modelNumber": "UN70TU7000BXZA",
      "brand": "Samsung",
      "year": 2018,
      "color": "Black",
      "series": "7",
      "price": 749.99,
      "screenResolution": '4K(2160p)',
      "screenSize": 70,
      "displayType": "LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amzon Alexa,Google Assistant",
      "box-size": "40.7(H), 7.5(w),68.7(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6429/6429416_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Insignia 6398122
    {
      "idProduct": 6398122,
      "nameProduct": " 40\" Class N10 Series LED Full HD TV",
      "category": "TV",
      "modelNumber": "NS-40D510NA21",
      "brand": "Insignia™",
      "year": 2020,
      "color": "Black",
      "series": "N10",
      "price": 239.99,
      "screenResolution": 'Full HD',
      "screenSize": 40,
      "displayType": "LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Not available",
      "box-size": "24,3(H), 40.4(w),5.8(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6398/6398122_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Insignia 63955127
    {
      "idProduct": 63955127,
      "nameProduct": " 32\" Class N10 Series LED HD TV",
      "category": "TV",
      "modelNumber": "NS-32D310NA21",
      "brand": "Insignia™",
      "year": 2020,
      "color": "Black",
      "series": "N10",
      "price": 169.99,
      "screenResolution": "HD(720p)",
      "screenSize": 32,
      "displayType": "LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Not available",
      "box-size": "19.5(H), 32.5(w),5.2(depth)",
      "shipping": "pickup",
      "image": " https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6395/6395127_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Vankyo - 6470323
    {
      "idProduct": 6470323,
      "nameProduct": " Leisure 3W PRO Wireless 720P Mini Projector",
      "category": "TV",//projector
      "modelNumber": "LS3W PRO",
      "brand": " Vankyo",
      "year": 2020,
      "color": "White",
      "price": 139.99,
      "screenResolution": "HD(720p)",
      "screenSize": 32,
      "displayType": "LCD",
      "Smart capable": "Yes",
      "Projector Use": "Gaming, Home Theater, Ultra Portable",
      "voice assistant": "Not available",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6470/6470323cv11d.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung 6401738
    {
      "idProduct": 6401738,
      "nameProduct": " 50\" Class 7 Series LED 4K UHD Smart Tizen TV",
      "category": "TV",
      "modelNumber": "UN50TU7000FXZA",
      "brand": "Samsung",
      "year": 2020,
      "color": "Gray",
      "series": "7",
      "price": 479.99,
      "screenResolution": "4K(2160p)",
      "screenSize": 50,
      "displayType": "LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amazone Alexa,Google Assistant",
      "box-size": "30.5(H), 50(w),5.8(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6401/6401738_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // LG 6453324
    {
      "idProduct": 6453324,
      "nameProduct": "55\" Class C1 Series OLED 4K UHD Smart webOS TV",
      "category": "TV",
      "modelNumber": "OLED55C1PUB",
      "brand": "LG",
      "year": 2021,
      "color": "Black",
      "series": "C1",
      "price": 1499.99,
      "screenResolution": "4K(2160p)",
      "screenSize": 55,
      "displayType": "OLED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amazone Alexa,Google Assistant",
      "box-size": "32.90(H), 8.14(w),52.95(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453324_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 6481727,
      "nameProduct": "70\" Class 4-Series LED 4K UHD HDR Smart Android TV",
      "category": "TV",
      "modelNumber": "70S434",
      "brand": "TCL",
      "year": 2021,
      "color": "Black",
      "series": "C1",
      "price": 829,
      "screenResolution": "4K(2160p)",
      "screenSize": 70,
      "displayType": "LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Google Assistant",
      "box-size": "42.9(H), 68.14(w),8(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6481/6481727_sd.jpg;maxHeight=640;maxWidth=550"
    },
    // APPLE products
    // Iphones:
    // Iphone 13 mini -6443301
    {
      "idProduct": 6443301,
      "category": "apple",
      "nameProduct": "iPhone 13 mini 5G 128GB",
      "brand": "Apple",
      "screenSize": 70,
      //  "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "PhoneStyle": "Smartphone",
      "modelNumber": "MLHM3LL/A",
      "Series": "iPhone 13",
      "color": "Black",
      "price": 650,
      "year": 2020,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443301_sd.jpg;maxHeight=640;maxWidth=550",
    },
    //Iphone 13 -6443289
    {
      "idProduct": 6443289,
      "category": "apple",
      "screenSize": 70,
      "nameProduct": "Apple - iPhone 13 5G 128GB - Blue (Verizon)",
      "brand": "Apple",
      //  "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "Phone Style": "Smartphone",
      "modelNumber": "MLHM3LL/A",
      "Series": "iPhone 13",
      "color": "Blue",
      "price": 699,
      "year": 2021,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443289_sd.jpg;maxHeight=640;maxWidth=550",
    },
    //
    // Iphone 13 Pro-6443321
    {
      "idProduct": 6443321,
      "category": "apple",
      "nameProduct": "iPhone 13 Pro 5G 128GB",
      "brand": "Apple",
      "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "Phone Style": "Smartphone",
      "modelNumber": "MLHM3LL/A",
      "Series": "iPhone 13",
      "screenSize": 70,
      "price": 699,
      "year": 2020,
      "color": "Blue",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443321_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Iphone 13 Pro Max
    {
      "idProduct": 6443337,
      "category": "apple",
      "screenSize": 70,
      "nameProduct": "iPhone 13 Pro Max 5G 128GB",
      "brand": "Apple",
      "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "Phone Style": "Smartphone",
      "modelNumber": "MLHM3LL/A",
      "Series": "iPhone 13",
      "price": 699,
      "year": 2021,
      "color": " Blue",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443337_sd.jpg;maxHeight=640;maxWidth=550 ",
    },
    //Macbooks ,ipads, airpod,
    {
      "idProduct": 6450853,
      "category": "cellPhone",
      "category": "apple",
      "nameProduct": "MacBook Pro 14\" Laptop - Apple M1 Pro chip - 16GB Memory - 512GB SSD (Latest Model)",
      "brand": "Apple",
      "Casing Material": "luminum",
      "modelNumber": "MKGP3LL/A",
      "year": 2021,
      "color": "Gray",
      "screenSize": 14.2,
      "screenResolution": "3024 x 1964",
      "Processor Cores": "8-core",
      "price": 1999,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6450/6450853_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 4001811,
      "category": "apple",
      "nameProduct": "10.2-Inch iPad (Latest Model) with Wi-Fi - 64GB",
      "brand": "Apple",
      "modelNumber": "MK2L3LL/A",
      "Model Family": "Apple iPad",
      "color": "Silver",
      "screenSize": 10.2,
      "screenResolution": "2160 x 1620",
      "price": 329.99,
      "year": 2020,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4901/4901811_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 6373463,
      "category": "apple",
      "nameProduct": "AirPods Max",
      "brand": "Apple",
      "Additional Accessories Included": "Smart Case,Lightning to USB-C Cable",
      "modelNumber": "MGYJ3AM/A",
      "Series": "AirPods Max",
      "price": 219.99,
      "year": 2020,
      "color": "Silver",
      "size": 549,
      "screenSize": 70,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6373/6373463_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 4900942,
      "category": "apple",
      "nameProduct": "AirPods Pro (with Magsafe Charging Case)",
      "brand": "Apple",
      "Additional Accessories Included": "MagSafe Charging Case, Silicone ear tips (three sizes), Lightning to USB-C Cable",
      "Ear Tip Sizes Included": "Large, Medium, Small",
      "modelNumber": "MLWK3AM/A",
      "Series": "AirPods Pro with Magsafe",
      "color": "White",
      "price": 219.99,
      "year": 2020,
      "screenSize": 70,
      
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4900/4900942_sd.jpg;maxHeight=640;maxWidth=550",
    },

    // example
    {
      "idProduct": 102,
      "nameProduct": "someName2",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 32,
      "color": "Gold",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6428/6428998_sd.jpg",

    },
    {
      "idProduct": 103,
      "nameProduct": "someName3",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 40,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 104,
      "nameProduct": "someName4",
      "category": "TV",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD 2",
      "screenSize": 75,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453321_sd.jpg",

    },
    {
      "idProduct": 105,
      "nameProduct": "someName8",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 2350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 50,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6471/6471189_sd.jpg",

    },
    {
      "idProduct": 106,
      "nameProduct": "someName7 89 LG",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 1350,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "type": "Smart",
      "displayType": "Full HD 2",
      "screenSize": 32,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6478/6478304cv11d.jpg",

    },
    {
      "idProduct": 107,
      "nameProduct": "someName6 45 LG",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 1250,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "type": "Smart",
      "displayType": "Full HD 2",
      "screenSize": 50,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6471/6471189_sd.jpg",

    },
    {
      "idProduct": 108,
      "nameProduct": "someName5 Sony",
      "category": "TV",
      "modelNumber": "ABC0011df123",
      "price": 1050,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 40,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6465/6465635_sd.jpg",

    },
    {
      "idProduct": 109,
      "nameProduct": "someName LG",
      "category": "TV",
      "modelNumber": "ABC0011df123",
      "price": 850,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 32,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453321_sd.jpg",

    },
    {
      "idProduct": 110,
      "nameProduct": "Sony",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 650,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 43,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6478/6478304cv11d.jpg",

    },
    {
      "idProduct": 111,
      "nameProduct": "someName5 Sony",
      "category": "TV",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 32,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454108_sd.jpg",

    },
    {
      "idProduct": 112,
      "nameProduct": "Sony 22",
      "category": "TV",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 43,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453321_sd.jpg",

    },
    {
      "idProduct": 113,
      "nameProduct": "someName6",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 2350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 32,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454254_sd.jpg",

    },
    {
      "idProduct": 114,
      "nameProduct": "someName5",
      "category": "TV",
      "modelNumber": "ABC0011df123",
      "price": 1350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 75,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6465/6465635_sd.jpg",

    },
    {
      "idProduct": 115,
      "nameProduct": "someName",
      "category": "TV",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 32,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454108_sd.jpg",

    },
    {
      "idProduct": 116,
      "nameProduct": "someName6",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 950,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 43,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6471/6471189_sd.jpg",

    },
    {
      "idProduct": 117,
      "nameProduct": "someName5",
      "category": "apple",
      "modelNumber": "ABC0011df123",
      "price": 988,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 40,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 118,
      "nameProduct": "someName apple",
      "category": "apple",
      "modelNumber": "ABC0011df123",
      "price": 2050,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 32,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 119,
      "nameProduct": "Arcade1Up - Super Pac-Man Counter-Cade",
      "category": "games",
      "modelNumber": "ABC0011df123",
      "price": 178,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 32,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6467/6467509cv11d.jpg",
      "displayType": "Full HD",
      "storageType": "Game SSD",
    },
    {
      "idProduct": 120,
      "nameProduct": "The Legend og Zelda",
      "category": "games",
      "modelNumber": "ABC0011df123",
      "price": 50,
      "shipping": "Free",
      "year": 2019,
      "brand": "NintendoSwitch",
      "type": "Smart",
      "displayType": "Full HD 2",
      "screenSize": 43,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6414/6414119_sd.jpg;maxHeight=640;maxWidth=550",
      "displayType": "Full HD",
      "storageType": "GSSD",
    },
    {
      "idProduct": 121,
      "nameProduct": "XBox Elite Wireless Controller",
      "category": "games",
      "modelNumber": "ABC0011df123",
      "price": 179,
      "shipping": "Free",
      "year": 2019,
      "brand": "Microsoft",
      "type": "Smart",
      "displayType": "Full HD",
      "screenSize": 55,
      "color": "Silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6352/6352703_sd.jpg;maxHeight=640;maxWidth=550",
      "displayType": "Full HD",
      "storageType": "GGSSD",
    },
  ]
}
