export const getData = function () {
  return [
    {
      "idProduct": 123001, //number
      "nameProduct": "someName", //string
      "category": "tv", // tv computers laptop tablets monitor cellPhone apple games app speakers headphones homeApp werrTechn
      "modelNumber": "ABC0011df123",
      "price": 350, // number
      "shipping": "Free", // or pickup, 
      "year": 2019, // 2018-2020-2021-2022
      "brand": "Apple", // HP Lenovo, Toshiba, LG, Samsung, Sony, Microsoft
      "type": "Curved", // Curved LED OLED
      "displayType": " Full HD", // HD 4K  4k-ULTRA-HP
      "screenSize": 32, // 32-40-43-50-55-70-75-85
      "color": "silver", // black, gold, gray, white
      "storageType": "SSD",
      "storage": 256, // 512GB -1TB
      "memoryRAM": 8, // 4-16-32 GB
      "processorModel": "Intel Core i3", // i5 i7 i9 AMD Ryzen 3-5-7 Apple M1-pro IntelPentium
      "screenResolution": "1600 x 900", // 3840 x 2160(4K) 3456 x 2234 3000x2000 
      "touchScreen": true, // false
      "productWeight": 3.75,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",
    },

    {
      "idProduct": 123002,
      "nameProduct": "Samsung",
      "category": "Computers",
      "modelNumber": "XE350XBA-K01US",
      "price": 299,
      "shipping": "Free", 
      "year": 2019,
      "brand": "Samsung",
      "type": "Smart",
      "displayType": "LED",
      "screenSize": 15.6,
      "color": "Platinum Titan",
      "storageType": "SSD",
      "memoryRAM": 16,
      "processorModel": "Intel Celeron",
      "screenResolution": "1920 x 1080",
      "touchScreen": false,
      "productWeight": 3.75,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6371/6371532_sd.jpg;maxHeight=640;maxWidth=550",
    },

    {
      "idProduct": 123003,
      "nameProduct": "MacBook Pro",
      "category": "Computers",
      "modelNumber": "MWP42LL/A",
      "price": 1.299,
      "shipping": "Free", 
      "year": 2020,
      "brand": "Apple",
      "displayType": "Retina Display",
      "screenSize": 13.3,
      "color": "Space gray",
      "storageType": "SSD",
      "memoryRAM": 16,
      "processorModel": "Intel 10th Generation Core i5",
      "screenResolution": "2560 x 1600 ",
      "touchScreen": false,
      "productWeight": 3.1,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6287/6287726_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123004,
      "nameProduct": "Dell",
      "category": "Computers",
      "modelNumber": "G7700-7231BLK-PUS",
      "price": 1.444,
      "shipping": "Free",
      "year": 2020,
      "brand": "Dell",
      "displayType": "LED",
      "screenSize": 17.3,
      "color": "Black",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 16,
      "processorModel": "Intel 10th Generation Core i7",
      "screenResolution": "1920 x 1080",
      "touchScreen": false,
      "productWeight": 6.53,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6416/6416473_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123005,
      "nameProduct": "Lenovo",
      "category": "Computers",
      "modelNumber": "82ND006QUS/82ND0002US",
      "price": 699,
      "shipping": "Free", 
      "year": 2021,
      "brand": "Lenovo",
      "displayType": " Full HD",
      "screenSize": 13.3,
      "color": "Abyss Blue with Fabric Cover",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 16,
      "processorModel": "AMD Ryzen 7 5000 Series",
      "screenResolution": "1920 x 1080",
      "touchScreen": true,
      "productWeight": 2.99,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455180_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123006,
      "nameProduct": "Asus",
      "category": "Computers",
      "modelNumber": "GU502LV-BI7N8",
      "price": 1.317,
      "shipping": "Free",
      "year": 2020,
      "brand": "Asus",
      "displayType": "LED",
      "screenSize": 15.6,
      "color": "Prism Black",
      "storageType": "SSD",
      "storage": 1024,
      "memoryRAM": 16,
      "processorModel": "i7-10750H",
      "screenResolution": "3840 x 2160",
      "touchScreen": false,
      "productWeight": 4.43,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6403/6403817_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123007,
      "nameProduct": "HP",
      "category": "Computers",
      "modelNumber": "15-dy2073dx",
      "price": 729.99,
      "shipping": "Free",
      "year": 2021,
      "brand": "HP",
      "displayType": "LED",
      "screenSize": 15.6,
      "color": "Natural Silver",
      "storageType": "SSD",
      "storage": 512,
      "memoryRAM": 16,
      "processorModel": "i7-1165G7",
      "screenResolution": "1920 x 1080",
      "touchScreen": true,
      "productWeight": 3.75,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477889_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123008,
      "nameProduct": "Acer",
      "category": "Computers",
      "modelNumber": "CB311-11H-K04N",
      "price": 129,
      "shipping": "Free",
      "year": 2021,
      "brand": "Acer",
      "displayType": "LED",
      "screenSize": 11.6,
      "color": "Silver",
      "storageType": "SSD eMMC",
      "storage": 256,
      "memoryRAM": 16,
      "processorModel": "MediaTek",
      "screenResolution": "1366 x 768",
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6471/6471196_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123009,
      "nameProduct": "UR55 Series 28 IPS 4K UHD Monitor",
      "category": "Computers",
      "modelNumber": "LU28R550UQNXZA",
      "price": 269.99,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "displayType": "LCD",
      "screenSize": 28,
      "color": "Black",
      "storageType": "SSD",
      "storage":  512,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "3840 x 2160",
      "productHeight": 14.7,
      "productWidth": "25.1",
      "standIncluded": true,
      "productWeight": 12.8,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6386/6386391_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123010,
      "nameProduct": "ASUS - TUF 23.8” FHD 1ms FreeSync Gaming Monitor (HDMI)",
      "category": "Computers",
      "modelNumber": "VG246H",
      "price": 179.99,
      "shipping": "Free",
      "year": 2021,
      "brand": "Asus",
      "displayType": "LED",
      "screenSize": 23.8,
      "color": "Black",
      "storageType": "SSD",
      "storage": 256, 
      "memoryRAM": 8, 
      "processorModel": "Intel Core i7", 
      "screenResolution": "1920 x 1080",
      "productHeight": 14.7,
      "productWidth": 21.46,
      "touchScreen": true,
      "productWeight": 13.36,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6450/6450752_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123011,
      "nameProduct": "35” Curved UltraWide QHD Monitor with USB Type C Connectivity",
      "category": "Computers",
      "modelNumber": "35WN75C-B",
      "price": 499.99,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "displayType": "LED",
      "screenSize": 35,
      "color": "Black",
      "storageType": "SSD",
      "storage": 1024, // 512GB -1TB
      "memoryRAM": 32,
      "processorModel": "Intel Core i7",
      "screenResolution": "3440 x 1440",
      "productHeight": 18.2,
      "productWidth": 32.7,
      "productWeight": 18.3,
      "touchScreen": false,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6437/6437477_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "idProduct": 123012,
      "nameProduct": "35” Curved UltraWide QHD Monitor with USB Type C Connectivity",
      "category": "Computers",
      "modelNumber": "66C0KCC3US",
      "price": 499.99,
      "shipping": "Free",
      "year": 2021, 
      "brand": "Lenovo",
      "displayType": "LED",
      "screenSize": 23.8,
      "color": "Black",
      "storageType": "SSD",
      "storage": 512, 
      "memoryRAM": 16,
      "processorModel": "Intel Core i5",
      "screenResolution": "1920 x 1080",
      "productHeight": 12.78,
      "productWidth": 21.28,
      "productWeight": 9.92,
      "curevedScreen": false,
      "standIncluded": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453641_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // 
    //LG -6453968
    {
      "idProduct": 123013,
      "nameProduct": "43\" Class UP7000 Series LED 4K UHD Smart webOS TV",
      "category": "tv",
      "modelNumber": "UP7000",
      "price": 1379,
      "shipping": "pickup",
      "year": "2020",
      "brand": "LG",
      "displayType":  "Led",
      "screenSize": 43,
      "colors": "Black",
      "screenResolution": "4K(2160p)",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453968_sd.jpg;maxHeight=640;maxWidth=550",
    },
    //SONY -6453208
    {
      "idProduct": 123014,
      "nameProduct": "65'Class BRAVIA XR X90J Series LED 4K UHD Smart Google TV",
      "category": "tv",
      "modelNumber":  "X9OJ",
      "price": 1499.99,
      "shipping": "pickup",
      "year": "2019",
      "brand": "Sony",
      "displayType": "Led",
      "screenSize": 65,
      "colors": "black",
      "screenResolution": '4K(2160p)',
      "BacklightType": "Full Array LOcal Dimming",
      "Smart capable": true,
      "Voice Assistanst Built-in": "Amazon Alexa,Google Assistant",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453208_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung - 6480602
    {
      "idProduct": 123015,
      "nameProduct": " 75' Class QN84A Neo QLED 4K UHD Smart Tizen TV",
      "category": "tv",
      "brand": "Samsung",
      "year": " 2020",
      "colors": "black",
      "Series": "X9OJ",
      "regularPrice": 2799.99,
      "currentPrice": 2649.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '75',
      "Display Type": "Led",
      "Backlight Type": "Full Array LOcal Dimming",
      "Smart capable": true,
      "Voice Assistanst Built-in": "Amazon Alexa,Google Assistant",
      "Shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6480/6480602cv20d.jpg;maxHeight=640;maxWidth=550",
    },
    // LG-6452992
    {
      "idProduct": 123016,
      "nameProduct": " 70” Class UP8070 Series LED 4K UHD Smart webOS TV",
      "category": "tv",
      "year": "2019",
      "Model": "70UP8070PUA",
      "brand": "LG",
      "colors": "black",
      "series": "UP8070",
      "regularPrice": 2799.99,
      "currentPrice": 2649.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '70',
      "Display Type": "Led",
      "Backlight Type": "Direct Lit",
      "Smart capable": "Yes",
      "Voice Assistanst Built-in": "Amazon Alexa,Google Assistant",
      "box-size": "33.3(H), 50(w) 6.1 inches(depth}",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452992_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung -6401735
    {
      "idProduct": 6401735,
      "nameProduct": " 65\" Class C1 Series OLED 4K UHD Smart webOS TV",
      "category": "tv",
      "Model": "OLED65C1PUB",
      "brand": "Samsung",
      "year": "2021",
      "colors": "Black",
      "series": "C1",
      "regularPrice": 499.99,
      "currentPrice": 399.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '64.5',
      "Display Type": "Oled",
      "Backlight Type": "Direct Lit",
      "Smart capable": "Yes",
      "VoiceAssistantBuilt-in": "GoogleAssistant,AmazonAlexa",
      "box-size": "37(h), 8.1496(w) 66.02 inches(depth}",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6401/6401735_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // LG 6453312
    {
      "idProduct": 6453312,
      "nameProduct": " 65\" Class C1 Series OLED 4K UHD Smart webOS TV",
      "category": "tv",
      "Model": "OLED65C1PUB",
      "brand": "LG",
      "year": "2021",
      "colors": "Black",
      "series": "C1",
      "regularPrice": 499.99,
      "currentPrice": 399.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '64.5inches',
      "Display Type": "OLED",
      "Smart capable": "Yes",
      "VoiceAssistantBuilt-in": "GoogleAssistant,AmazonAlexa",
      "box-size": "37.4015(H), 8.1496(w)  66.0236 inches(depth}",
      "shipping": "pickup",
      "images": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453312_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung -6453192
    {
      "idProduct": 6453192,
      "nameProduct": " 43\" Class Q60A Series QLED 4K UHD Smart Tizen TV",
      "category": "tv",
      "Model": "QN43Q60AAFXZA",
      "brand": "Samsung",
      "year": "2021",
      "colors": "Titan gray",
      "series": "Q60",
      "regularPrice": 599.99,
      "currentPrice": 499.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '43inches',
      "Display Type": "Edge Lit",
      "Smart capable": "Yes",
      "VoiceAssistantBuilt-in": "GoogleAssistant,AmazonAlexa",
      "box-size": "27(H), 42.4(w)  4.9(depth}",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453192_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // LG-6454719
    {
      "idProduct": 6454719,
      "nameProduct": " 65” Class UP7000 Series LED 4K UHD Smart webOS TV ",
      "category": "tv",
      "Model": "65UP7000PUA",
      "brand": "LG",
      "year": "2021",
      "colors": "Black",
      "series": "7000",
      "regularPrice": 619.99,
      "currentPrice": 499.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '65inches',
      "Display Type": " Direct Lit",
      "Smart capable": "Yes",
      "VoiceAssistantBuilt-in": "GoogleAssistant,AmazonAlexa",
      "box-size": "37.7952(H), 7.0078(w)  62.9921(depth}",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454719_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung -6401740
    {
      "idProduct": 6401740,
      "nameProduct": "43\"Class 7 Series LED 4K UHD Smart Tizen TV",
      "category": "tv",
      "Model": "UN43TU7000FXZA",
      "brand": "Samsung",
      "year": "2020",
      "colors": "Titan gray",
      "series": "7",
      "regularPrice": 399.99,
      "currentPrice": 350.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '43inches',
      "Display Type": " Direct Lit",
      "Smart capable": "Yes",
      "voice assistant": "not available",
      "box-size": "26.2(H), 42.6(w), 5.3(depth",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6401/6401740_sd.jpg;maxHeight=640; maxWidth=550",
    },

    {
      "idProduct": 6456970,
      "nameProduct": " 50\"Class F30 Series LED 4K UHD Smart Fire TV ",
      "category": "tv",
      "Model": "NS-50F301NA22",
      "brand": "Insignia™",
      "year": "2021",
      "colors": "black",
      "series": "F30 Series",
      "regularPrice": 449.99,
      "currentPrice": 349.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": '49.5inches',
      "Display Type": " Direct Lit",
      "Smart capable": "Yes",
      "voice assistant": "Amazon Alexa",
      "box-size": "31.8(H), 48(w), 5.8(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6456/6456970_sd.jpg;maxHeight=640;maxWidth=550"
    },
    // Sony - 6455218
    {
      "idProduct": "6455218",
      "nameProduct": " 65\" Class BRAVIA XR A80J Series OLED 4K UHD Smart Google TV",
      "category": "tv",
      "Model": "XR65A80J",
      "brand": "Sony",
      "year": "2021",
      "colors": "black",
      "series": "A80J",
      "regularPrice": 2299.99,
      "currentPrice": 2199.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": "69inches",
      "Display Type": " OLED",
      "Smart capable": "Yes",
      "voice assistant": "Amazon Alexa,Google Assistant",
      "box-size": "38(H), 64.37(w), 7.25(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455218_sd.jpg;maxHeight=640;maxWidth=550",
    },
    ///Insignia -6247254
    {
      "idProduct": "6247254",
      "nameProduct": " 32\" Class F20 Series LED HD Smart Fire TV",
      "category": "tv",
      "Model": "NS-32DF310NA19",
      "brand": "Insignia™",
      "year": "2018",
      "colors": "black",
      "series": "F20",
      "regularPrice": 199.99,
      "currentPrice": 149.99,
      "Resolution": 'HD(720)',
      "Screen Size Class": "32inches",
      "Display Type": " Standard LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amazon Alexa",
      "box-size": "20.1(H), 32.1(w),5.3(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6247/6247254_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // samsung -6452966
    {
      "idProduct": "6252966",
      "nameProduct": " 43\" Class 8000 Series LED 4K UHD Smart Tizen TV ",
      "category": "tv",
      "Model": " UN43AU8000FXZA",
      "brand": " Samsung",
      "year": "2021",
      "colors": "black",
      "series": "8000",
      "regularPrice": 499.99,
      "currentPrice": 379.99,
      "Resolution": 'HD(720)',
      "Screen Size Class": "32inches",
      "Display Type": " Standard LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amazon Alexa",
      "box-size": "26.8(H), 42.7(w),4.9(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452966cv12d.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung- 6451478
    {
      "idProduct": "6451478",
      "nameProduct": " 65\" Class Q80A Series QLED 4K UHD Smart Tizen TV ",
      "category": "tv",
      "Model": " QN65Q80AAFXZA",
      "brand": " Samsung",
      "year": "2021",
      "colors": "titan-black",
      "series": "Q80",
      "regularPrice": 1399.99,
      "currentPrice": 1199.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": "65 inches",
      "Display Type": " LED",
      "Smart capable": "Yes",
      "Backlight Type": "Full Array Local Dimming",
      "voice assistant": "Amazon Alexa,GoogleAssistant(Bixby",
      "box-size": "38(H), 63.8(w), 8.4(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6451/6451478_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung- 6453024
    {
      "idProduct": "6453024",
      "nameProduct": " 65\" Class 8000 Series LED 4K UHD Smart Tizen TV",
      "category": "tv",
      "Model": "UN65AU8000FXZA",
      "brand": " Samsung",
      "year": "2021",
      "colors": "black",
      "series": "8000",
      "regularPrice": 799.99,
      "currentPrice": 679.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": "65 inches",
      "Display Type": " LED",
      "Smart capable": "Yes",
      "Backlight Type": "Full Array Local Dimming",
      "voice assistant": "Bixby,Google Assistant",
      "box-size": "37.4(H), 63.5(w), 65(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453024_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      // Samsung 642916
      "idProduct": "642916",
      "nameProduct": " 70\" Class 7 Series LED 4K UHD Smart Tizen TV",
      "category": "tv",
      "Model": "UN70TU7000BXZA",
      "brand": " Samsung",
      "year": "2021",
      "colors": "Titan black",
      "series": "7",
      "regularPrice": 749.99,
      "currentPrice": 679.99,
      "Resolution": '4K(2160p)',
      "Screen Size Class": "70inches",
      "Display Type": " LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amzon Alexa,Google Assistant",
      "box-size": "40.7(H), 7.5(w),68.7(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6429/6429416_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Insignia 6398122
    {
      "idProduct": "6398122",
      "nameProduct": " 40\" Class N10 Series LED Full HD TV",
      "category": "tv",
      "Model": "NS-40D510NA21",
      "brand": " Insignia™",
      "year": "2020",
      "colors": "black",
      "series": "N10",
      "regularPrice": 239.99,
      "currentPrice": 199.99,
      "Resolution": 'Full HD(1080p)',
      "Screen Size Class": "40 inches",
      "Display Type": " LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Not available",
      "box-size": "24,3(H), 40.4(w),5.8(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6398/6398122_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Insignia 63955127
    {
      "idProduct": "63955127",
      "nameProduct": " 32\" Class N10 Series LED HD TV",
      "category": "tv",
      "Model": "NS-32D310NA21",
      "brand": " Insignia™",
      "year": "2020",
      "colors": "black",
      "series": "N10",
      "regularPrice": 169.99,
      "currentPrice": 129.99,
      "Resolution": ' HD(720p)',
      "Screen Size Class": "32 inches",
      "Display Type": " LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Not available",
      "box-size": "19.5(H), 32.5(w),5.2(depth)",
      "shipping": "pickup",
      "image": " https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6395/6395127_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Vankyo - 6470323
    {
      "idProduct": "6470323",
      "nameProduct": " Leisure 3W PRO Wireless 720P Mini Projector",
      "category": "tv",//projector
      "Model": "LS3W PRO",
      "brand": " Vankyo",
      "year": "false",
      "colors": "white",
      "regularPrice": 139.99,
      "currentPrice": 129.99,
      "Resolution": "HD(720p)",
      "Screen Size Class": "32 inches",
      "Display Type": " LCD",
      "Smart capable": "Yes",
      "Projector Use": "Gaming, Home Theater, Ultra Portable",
      "voice assistant": "Not available",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6470/6470323cv11d.jpg;maxHeight=640;maxWidth=550",
    },
    // Samsung 6401738
    {
      "idProduct": "6401738",
      "nameProduct": " 50\" Class 7 Series LED 4K UHD Smart Tizen TV",
      "category": "tv",
      "Model": "UN50TU7000FXZA",
      "brand": " Samsung",
      "year": "2020",
      "colors": "gray",
      "series": "7",
      "regularPrice": 479.99,
      "currentPrice": 439.99,
      "Resolution": "4K(2160p)",
      "Screen Size Class": "50inches",
      "Display  Type": " LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amazone Alexa,Google Assistant",
      "box-size": "30.5(H), 50(w),5.8(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6401/6401738_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // LG 6453324
    {
      "idProduct": "6453324",
      "nameProduct": "55\" Class C1 Series OLED 4K UHD Smart webOS TV",
      "category": "tv",
      "model": "OLED55C1PUB",
      "brand": "LG",
      "year": "2021",
      "colors": "black;",
      "series": "C1",
      "Price": 1499.99,
      "Resolution": "4K(2160p)",
      "Screen Size Class": "55 inches",
      "Display  Type": " OLED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Amazone Alexa,Google Assistant",
      "box-size": "32.90(H), 8.14(w),52.95(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453324_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // TCL-6481727
    {
      "idProduct": "6481727",
      "nameProduct": "70\" Class 4-Series LED 4K UHD HDR Smart Android TV",
      "category": "tv",
      "model": "70S434",
      "brand": "TCL",
      "year": "2021",
      "colors": "black;",
      "series": "C1",
      "original price": 829,
      "current price": 599,
      "Resolution": "4K(2160p)",
      "Screen Size Class": "70 inches",
      "Display  Type": " LED",
      "Smart capable": "Yes",
      "Backlight Type": "Direct Lit",
      "voice assistant": "Google Assistant",
      "box-size": "42.9(H), 68.14(w),8(depth)",
      "shipping": "pickup",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6481/6481727_sd.jpg;maxHeight=640;maxWidth=550"
    },
    // APPLE products
    // Iphones:
    // Iphone 13 mini -6443301
    {
      "idProduct ": 6443301,
      "category": "apple",
      "Product Name": "iPhone 13 mini 5G 128GB",
      "brand": "Apple",
      //  "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "Phone Style": "Smartphone",
      "Model Number": "MLHM3LL/A",
      "Series": "iPhone 13",
      "Color": "Midnight",
      "Price": "26.6 per month",
      "Color": "Black",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443301_sd.jpg;maxHeight=640;maxWidth=550",
    },
    //Iphone 13 -6443289
    {
      "idProduct ": 6443289,
      "category": "apple",
      "Product Name": "Apple - iPhone 13 5G 128GB - Blue (Verizon)",
      "brand": "Apple",
      //  "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "Phone Style": "Smartphone",
      "Model Number": "MLHM3LL/A",
      "Series": "iPhone 13",
      "Color": "Blue",
      "Price": 699,
      "Color": "Blue",
      "Price": "26.6/per month",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443289_sd.jpg;maxHeight=640;maxWidth=550",
    },
    //
    // Iphone 13 Pro-6443321
    {
      "id ": 6443321,
      "category": "apple",
      "Product Name": "iPhone 13 Pro 5G 128GB",
      "brand": "Apple",
      "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "Phone Style": "Smartphone",
      "Model Number": "MLHM3LL/A",
      "Series": "iPhone 13",
      "Color": "Blue",
      "Price": 699,
      "Color": "Blue",
      "Price": "26.6/per month",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443321_sd.jpg;maxHeight=640;maxWidth=550",
    },
    // Iphone 13 Pro Max
    {
      "id ": 6443337,
      "category": "apple",
      "Product Name": "iPhone 13 Pro Max 5G 128GB",
      "brand": "Apple",
      "Device Manufacturer": "Apple",
      "Additional Hardware Included": "USB-C to Lightning Cable",
      "Phone Style": "Smartphone",
      "Model Number": "MLHM3LL/A",
      "Series": "iPhone 13",
      "Color": "Blue",
      "Price": 699,
      "Color": " Sierra Blue",
      "Price": "45.6/per month",
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443337_sd.jpg;maxHeight=640;maxWidth=550 ",
    },
    //Macbooks ,ipads, airpod,
    {
      "id": 6450853,
      "category": "apple",
      "Product Name": "MacBook Pro 14\" Laptop - Apple M1 Pro chip - 16GB Memory - 512GB SSD (Latest Model)",
      "brand": "Apple",
      "Casing Material": "luminum",
      "Model Number": "MKGP3LL/A",
      "Year of Release": 2021,
      "Color": "Space Gray",
      "Screen Size": "14.2 inches",
      "Screen Resolution": "3024 x 1964",
      "Processor Cores": "8-core",
      "price": 1999,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6450/6450853_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "id": 4001811,
      "category": "apple",
      "Product Name": "10.2-Inch iPad (Latest Model) with Wi-Fi - 64GB",
      "brand": "Apple",
      "Model Number": "MK2L3LL/A",
      "Model Family": "Apple iPad",
      "Year of Release": "2021",
      "Color": "Silver",
      "Screen Size": "10.2 inches",
      "Screen Resolution": "2160 x 1620",
      "price": 329.99,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4901/4901811_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "id": 6373463,
      "category": "apple",
      "Product Name": "AirPods Max",
      "brand": "Apple",
      "Additional Accessories Included": "Smart Case,Lightning to USB-C Cable",
      "Model Number": "MGYJ3AM/A",
      "Series": "AirPods Max",
      "Color": "Silver",
      "size": 549,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6373/6373463_sd.jpg;maxHeight=640;maxWidth=550",
    },
    {
      "id": 4900942,
      "category": "apple",
      "Product Name": "AirPods Pro (with Magsafe Charging Case)",
      "brand": "Apple",
      "Additional Accessories Included": "MagSafe Charging Case, Silicone ear tips (three sizes), Lightning to USB-C Cable",
      "Ear Tip Sizes Included": "Large, Medium, Small",
      "Model Number": "MLWK3AM/A",
      "Series": "AirPods Pro with Magsafe",
      "Color": "White",
      "price": 219.99,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4900/4900942_sd.jpg;maxHeight=640;maxWidth=550",
    },

    // example
    {
      "idProduct": 102,
      "nameProduct": "someName2",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "gold",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 103,
      "nameProduct": "someName3",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 104,
      "nameProduct": "someName4",
      "category": "tv",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 105,
      "nameProduct": "someName8",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 106,
      "nameProduct": "someName7 89 LG",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 107,
      "nameProduct": "someName6 45 LG",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 108,
      "nameProduct": "someName5 Sony",
      "category": "tv",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 109,
      "nameProduct": "someName LG",
      "category": "tv",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "LG",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 110,
      "nameProduct": "Sony",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 111,
      "nameProduct": "someName5 Sony",
      "category": "tv",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 112,
      "nameProduct": "Sony 22",
      "category": "tv",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Sony",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 113,
      "nameProduct": "someName6",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 114,
      "nameProduct": "someName5",
      "category": "tv",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 115,
      "nameProduct": "someName",
      "category": "tv",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 116,
      "nameProduct": "someName6",
      "category": "computers",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 117,
      "nameProduct": "someName5",
      "category": "apple",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 118,
      "nameProduct": "someName apple",
      "category": "apple",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 119,
      "nameProduct": "someName6 apple",
      "category": "apple",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 120,
      "nameProduct": "some games",
      "category": "games",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Apple",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
    {
      "idProduct": 121,
      "nameProduct": "someName games3",
      "category": "games",
      "modelNumber": "ABC0011df123",
      "price": 350,
      "shipping": "Free",
      "year": 2019,
      "brand": "Samsung",
      "type": "Smart",
      "screenType": " Full HD",
      "screenSize": 32,
      "color": "silver",
      "storage": 256,
      "memoryRAM": 8,
      "processorModel": "Intel Core i3",
      "screenResolution": "1600 x 900",
      "touchScreen": true,
      "image": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550",

    },
  ]
}