export const getData = function() {
    return [
        { "idProduct": 101999, //number
            "nameProduct" : "someName" , //string
            "category" : "tv", // tv computers laptop tablets monitor cellPhone apple games app speakers headphones homeApp werrTechn
            "modelNumber" : "ABC0011df123",
            "price" : 350, // number
            "shipping" : "Free", // or pickup, 
            "year" : 2019, // 2018-2020-2021-2022
            "brand" : "Apple" , // HP Lenovo, Toshiba, LG, Samsung, Sony, Microsoft
            "type" : "Curved", // Curved LED OLED
            "screenType" : " Full HD", // HD 4K  4k-ULTRA-HP
            "screenSize" : 32, // 32-40-43-50-55-70-75-85
            "color" : "silver", // black, gold, gray, white
            "storage" : 256, // 512GB -1TB
            "memoryRAM" : 8, // 4-16-32 GB
            "processorModel" : "Intel Core i3", // i5 i7 i9 AMD Ryzen 3-5-7 Apple M1-pro IntelPentium
            "screenResolution" : "1600 x 900", // 3840 x 2160(4K) 3456 x 2234 3000x2000 
            "touchScreen" : true, // false
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },

          {  "idProduct": 10,
    "nameProduct" : "Samsung",
    "category" : "Computers",
    "modelNumber" : "XE350XBA-K01US",
    "price" : 299,
    "year" : 2019,
    "brand" : "Samsung" ,
    "type" : "Smart",
    "displayType" : "LED",
    "screenSize" : 15.6,
    "color" : "Platinum Titan",
    "storageType" : "SSD",
    "memoryRAM" : 16,
    "processorModel" : "Intel Celeron",
    "screenResolution" : "1920 x 1080",
    "touchScreen" : false,
    "productWeight" : 3.75,
    "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6371/6371532_sd.jpg;maxHeight=640;maxWidth=550",
},

{ "idProduct": 11,
    "nameProduct" : "MacBook Pro" ,
    "category" : "Computers",
    "modelNumber" : "MWP42LL/A",
    "price" : 1.299,
    "year" : 2020,
    "brand" : "Apple" ,
    "screenType" : "Retina Display",
    "screenSize" : 13.3,
    "color" : "Space gray",
    "storageType" : "SSD",
    "memoryRAM" : 16,
    "processorModel" : "Intel 10th Generation Core i5",
    "screenResolution" : "2560 x 1600 ",
    "touchScreen" : false,
    "productWeight" : 3.1,
    "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6287/6287726_sd.jpg;maxHeight=640;maxWidth=550",
},
{
"idProduct": 12,
    "nameProduct" : "Dell" ,
    "category" : "Computers",
    "modelNumber" : "G7700-7231BLK-PUS",
    "price" : 1.444,
    "year" : 2020,
    "brand" : "Dell" ,
    "displayType" : "LED",
    "screenSize" : 17.3,
    "color" : "Black",
    "storageType" : "SSD",
    "memoryRAM" : 16,
    "processorModel" : "Intel 10th Generation Core i7",
    "screenResolution" : "1920 x 1080",
    "touchScreen" : false,
    "productWeight" : 6.53,
    "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6416/6416473_sd.jpg;maxHeight=640;maxWidth=550",
},
{"idProduct": 13,
    "nameProduct" : "Lenovo" ,
    "category" : "Computers",
    "modelNumber" : "82ND006QUS/82ND0002US",
    "price" : 699,
    "year" : 2021,
    "brand" : "Lenovo" ,
    "screenSize" : 13.3,
    "color" : "Abyss Blue with Fabric Cover",
    "storageType" : "SSD",
    "memoryRAM" : 16,
    "processorModel" : "AMD Ryzen 7 5000 Series",
    "screenResolution" : "1920 x 1080",
    "touchScreen" : true,
    "productWeight" : 2.99,
    "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455180_sd.jpg;maxHeight=640;maxWidth=550",
},
{"idProduct": 14,
    "nameProduct" : "Asus" ,
    "category" : "Computers",
    "modelNumber" : "GU502LV-BI7N8",
    "price" : 1.317,
    "year" : 2020,
    "brand" : "Asus",
    "displayType": "LED",
    "screenSize" : 15.6,
    "color" : "Prism Black",
    "storageType" : "SSD",
    "memoryRAM" : 16,
    "processorModel" : "i7-10750H",
    "screenResolution" : "3840 x 2160",
    "touchScreen" : false,
    "productWeight" : 4.43,
    "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6403/6403817_sd.jpg;maxHeight=640;maxWidth=550",
},
{
    "idProduct": 15,
    "nameProduct" : "HP" ,
    "category" : "Computers",
    "modelNumber" : "15-dy2073dx",
    "price" : 729.99,
    "year" : 2021,
    "brand" : "HP" ,
    "displayType": "LED",
    "screenSize" : 15.6,
    "color" : "Natural Silver",
    "storageType" : "SSD",
    "memoryRAM" : 16,
    "processorModel" : "i7-1165G7",
    "screenResolution" : "1920 x 1080",
    "touchScreen" : true,
    "productWeight" : 3.75,
    "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477889_sd.jpg;maxHeight=640;maxWidth=550",
},
{
"idProduct": 16,
    "nameProduct" : "Acer" ,
    "category" : "Computers",
    "modelNumber" : "CB311-11H-K04N",
    "price" : 129,
    "year" : 2021,
    "brand" : "Acer" ,
    "displayType": "LED",
    "screenSize" : 11.6,
    "color" : "Silver",
    "storageType" : "SSD",
    "memoryRAM" : 16,
    "processorModel" : "MediaTek",
    "screenResolution" : "1366 x 768",
    "touchScreen" : false,
    "storageType" : "eMMC",
    "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6471/6471196_sd.jpg;maxHeight=640;maxWidth=550",
},
{
"idProduct": 17,
    "nameProduct" : "UR55 Series 28 IPS 4K UHD Monitor",
    "category" : "Computers",
    "modelNumber" : "LU28R550UQNXZA",
    "price" : 269.99,
    "displayType" : "LCD",
    "brand" : "Samsung" ,
    "screenSize" : 28,
    "color" : "Black",
    "maxResolution" : "3840 x 2160",
    "productHeight" : 14.7,
    "productWidth" : "25.1",
    "curevedScreen" : false,
    "standIncluded" : true,
    "productWeight" : 12.8,
    "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6386/6386391_sd.jpg;maxHeight=640;maxWidth=550",
},
{
    "idProduct": 18,
    "nameProduct" : "ASUS - TUF 23.8” FHD 1ms FreeSync Gaming Monitor (HDMI)",
    "category" : "Computers",
    "modelNumber" : "VG246H",
    "price" : 179.99,
    "displayType" : "LED",
    "brand" : "Asus" ,
    "screenSize" : 23.8,
    "color" : "Black",
    "maxResolution" : "1920 x 1080",
    "productHeight" : 14.7,
    "productWidth" : 21.46,
    "curevedScreen" : false,
    "standIncluded" : true,
    "productWeight" : 13.36,
    "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6450/6450752_sd.jpg;maxHeight=640;maxWidth=550",
},
{
"idProduct": 19,
    "nameProduct" : "35” Curved UltraWide QHD Monitor with USB Type C Connectivity",
    "category" : "Computers",
    "modelNumber" : "35WN75C-B",
    "price" : 499.99,
    "displayType" : "LED",
    "brand" : "LG" ,
    "screenSize" : 35,
    "color" : "Black",
    "maxResolution" : "3440 x 1440",
    "productHeight" : 18.2,
    "productWidth" : 32.7,
    "productWeight" : 18.3,
    "touchScreen" : false,
    "curevedScreen" : true,
    "standIncluded" : true,
    "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6437/6437477_sd.jpg;maxHeight=640;maxWidth=550",
},
{
    "idProduct": 20,
        "nameProduct" : "35” Curved UltraWide QHD Monitor with USB Type C Connectivity",
        "category" : "Computers",
        "modelNumber" : "66C0KCC3US",
        "price" : 499.99,
        "displayType" : "LED",
        "brand" : "Lenovo" ,
        "screenSize" : 23.8,
        "color" : "Black",
        "maxResolution" : "1920 x 1080",
        "productHeight" : 12.78,
        "productWidth" : 21.28,
        "productWeight" : 9.92,
        "curevedScreen" : false,
        "standIncluded" : true,
        "image":"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453641_sd.jpg;maxHeight=640;maxWidth=550",
},
        
          { "idProduct": 102, 
            "nameProduct" : "someName2" , 
            "category" : "computers", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "Samsung" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "gold", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 103, 
            "nameProduct" : "someName3" , 
            "category" : "computers", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "Samsung" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "silver", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 104, 
            "nameProduct" : "someName4" , 
            "category" : "tv", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "Apple" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "silver", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 105, 
            "nameProduct" : "someName8" , 
            "category" : "computers", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "Apple" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "silver", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 106, 
            "nameProduct" : "someName7 89 LG" , 
            "category" : "computers", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "LG" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "silver", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 107, 
            "nameProduct" : "someName6 45 LG" , 
            "category" : "computers", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "LG" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "silver", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 108, 
            "nameProduct" : "someName5 Sony" , 
            "category" : "tv", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "Sony" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "silver", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 109, 
            "nameProduct" : "someName LG" , 
            "category" : "tv", 
            "modelNumber" : "ABC0011df123",
            "price" : 350, 
            "shipping" : "Free", 
            "year" : 2019, 
            "brand" : "LG" , 
            "type" : "Smart", 
            "screenType" : " Full HD", 
            "screenSize" : 32, 
            "color" : "silver", 
            "storage" : 256, 
            "memoryRAM" : 8, 
            "processorModel" : "Intel Core i3", 
            "screenResolution" : "1600 x 900",
            "touchScreen" : true,
            "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
            
          },
          { "idProduct": 110, 
          "nameProduct" : "Sony computers" , 
          "category" : "computers", 
          "modelNumber" : "ABC0011df123",
          "price" : 350, 
          "shipping" : "Free", 
          "year" : 2019, 
          "brand" : "Sony" , 
          "type" : "Smart", 
          "screenType" : " Full HD", 
          "screenSize" : 32, 
          "color" : "silver", 
          "storage" : 256, 
          "memoryRAM" : 8, 
          "processorModel" : "Intel Core i3", 
          "screenResolution" : "1600 x 900",
          "touchScreen" : true,
          "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
          
        },
        { "idProduct": 111, 
          "nameProduct" : "someName5 Sony" , 
          "category" : "tv", 
          "modelNumber" : "ABC0011df123",
          "price" : 350, 
          "shipping" : "Free", 
          "year" : 2019, 
          "brand" : "Sony" , 
          "type" : "Smart", 
          "screenType" : " Full HD", 
          "screenSize" : 32, 
          "color" : "silver", 
          "storage" : 256, 
          "memoryRAM" : 8, 
          "processorModel" : "Intel Core i3", 
          "screenResolution" : "1600 x 900",
          "touchScreen" : true,
          "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
          
        },
        { "idProduct": 112, 
          "nameProduct" : "Sony 22" , 
          "category" : "tv", 
          "modelNumber" : "ABC0011df123",
          "price" : 350, 
          "shipping" : "Free", 
          "year" : 2019, 
          "brand" : "Sony" , 
          "type" : "Smart", 
          "screenType" : " Full HD", 
          "screenSize" : 32, 
          "color" : "silver", 
          "storage" : 256, 
          "memoryRAM" : 8, 
          "processorModel" : "Intel Core i3", 
          "screenResolution" : "1600 x 900",
          "touchScreen" : true,
          "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
          
        },
        { "idProduct": 113, 
        "nameProduct" : "someName6 computers" , 
        "category" : "computers", 
        "modelNumber" : "ABC0011df123",
        "price" : 350, 
        "shipping" : "Free", 
        "year" : 2019, 
        "brand" : "Apple" , 
        "type" : "Smart", 
        "screenType" : " Full HD", 
        "screenSize" : 32, 
        "color" : "silver", 
        "storage" : 256, 
        "memoryRAM" : 8, 
        "processorModel" : "Intel Core i3", 
        "screenResolution" : "1600 x 900",
        "touchScreen" : true,
        "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
        
      },
      { "idProduct": 114, 
        "nameProduct" : "someName5" , 
        "category" : "tv", 
        "modelNumber" : "ABC0011df123",
        "price" : 350, 
        "shipping" : "Free", 
        "year" : 2019, 
        "brand" : "Apple" , 
        "type" : "Smart", 
        "screenType" : " Full HD", 
        "screenSize" : 32, 
        "color" : "silver", 
        "storage" : 256, 
        "memoryRAM" : 8, 
        "processorModel" : "Intel Core i3", 
        "screenResolution" : "1600 x 900",
        "touchScreen" : true,
        "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
        
      },
      { "idProduct": 115, 
        "nameProduct" : "someName" , 
        "category" : "tv", 
        "modelNumber" : "ABC0011df123",
        "price" : 350, 
        "shipping" : "Free", 
        "year" : 2019, 
        "brand" : "Apple" , 
        "type" : "Smart", 
        "screenType" : " Full HD", 
        "screenSize" : 32, 
        "color" : "silver", 
        "storage" : 256, 
        "memoryRAM" : 8, 
        "processorModel" : "Intel Core i3", 
        "screenResolution" : "1600 x 900",
        "touchScreen" : true,
        "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
        
      },
      { "idProduct": 116, 
      "nameProduct" : "someName6 computers" , 
      "category" : "computers", 
      "modelNumber" : "ABC0011df123",
      "price" : 350, 
      "shipping" : "Free", 
      "year" : 2019, 
      "brand" : "Apple" , 
      "type" : "Smart", 
      "screenType" : " Full HD", 
      "screenSize" : 32, 
      "color" : "silver", 
      "storage" : 256, 
      "memoryRAM" : 8, 
      "processorModel" : "Intel Core i3", 
      "screenResolution" : "1600 x 900",
      "touchScreen" : true,
      "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
      
    },
    { "idProduct": 117, 
      "nameProduct" : "someName5" , 
      "category" : "apple", 
      "modelNumber" : "ABC0011df123",
      "price" : 350, 
      "shipping" : "Free", 
      "year" : 2019, 
      "brand" : "Apple" , 
      "type" : "Smart", 
      "screenType" : " Full HD", 
      "screenSize" : 32, 
      "color" : "silver", 
      "storage" : 256, 
      "memoryRAM" : 8, 
      "processorModel" : "Intel Core i3", 
      "screenResolution" : "1600 x 900",
      "touchScreen" : true,
      "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
      
    },
    { "idProduct": 118, 
      "nameProduct" : "someName apple" , 
      "category" : "apple", 
      "modelNumber" : "ABC0011df123",
      "price" : 350, 
      "shipping" : "Free", 
      "year" : 2019, 
      "brand" : "Apple" , 
      "type" : "Smart", 
      "screenType" : " Full HD", 
      "screenSize" : 32, 
      "color" : "silver", 
      "storage" : 256, 
      "memoryRAM" : 8, 
      "processorModel" : "Intel Core i3", 
      "screenResolution" : "1600 x 900",
      "touchScreen" : true,
      "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
      
    },
    { "idProduct": 119, 
    "nameProduct" : "someName6 apple" , 
    "category" : "apple", 
    "modelNumber" : "ABC0011df123",
    "price" : 350, 
    "shipping" : "Free", 
    "year" : 2019, 
    "brand" : "Apple" , 
    "type" : "Smart", 
    "screenType" : " Full HD", 
    "screenSize" : 32, 
    "color" : "silver", 
    "storage" : 256, 
    "memoryRAM" : 8, 
    "processorModel" : "Intel Core i3", 
    "screenResolution" : "1600 x 900",
    "touchScreen" : true,
    "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
    
  },
  { "idProduct": 120, 
    "nameProduct" : "some games" , 
    "category" : "games", 
    "modelNumber" : "ABC0011df123",
    "price" : 350, 
    "shipping" : "Free", 
    "year" : 2019, 
    "brand" : "Apple" , 
    "type" : "Smart", 
    "screenType" : " Full HD", 
    "screenSize" : 32, 
    "color" : "silver", 
    "storage" : 256, 
    "memoryRAM" : 8, 
    "processorModel" : "Intel Core i3", 
    "screenResolution" : "1600 x 900",
    "touchScreen" : true,
    "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
    
  },
  { "idProduct": 121, 
    "nameProduct" : "someName games3" , 
    "category" : "games", 
    "modelNumber" : "ABC0011df123",
    "price" : 350, 
    "shipping" : "Free", 
    "year" : 2019, 
    "brand" : "Samsung" , 
    "type" : "Smart", 
    "screenType" : " Full HD", 
    "screenSize" : 32, 
    "color" : "silver", 
    "storage" : 256, 
    "memoryRAM" : 8, 
    "processorModel" : "Intel Core i3", 
    "screenResolution" : "1600 x 900",
    "touchScreen" : true,
    "image" : "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477887_sd.jpg;maxHeight=640;maxWidth=550" ,
    
  },
        ]
    }